version: '3.8'

services:
  simple_recip_application:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=release

    image: simple_recip_application:1.12.42

    container_name: simple_recip_application

    ports:
      - "4242:4242"

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:4242
      ASPNETCORE_HTTP_PORTS: 4242
      
      ConnectionStrings__DefaultConnection: "Data Source=/app/Data/recipes.db"
      
      ApplicationVersion : "1.12.42"
      
      FeatureManagement__RecipeFeature: true
      FeatureManagement__IngredientFeature: true
      FeatureManagement__ImportationFeature: false
      FeatureManagement__RecipeImportationFeature: false
      FeatureManagement__RecipeManagementFeature: false
      FeatureManagement__IngredientManagementFeature: false
      FeatureManagement__RecipePlanningFeature: false
      FeatureManagement__PlanifiedRecipesAutomaticaly: false
      FeatureManagement__ProductManagementFeature: false
      FeatureManagement__UserPantryManagement: false
      FeatureManagement__TagManagement: false
      
      FileSettings__MaxAllowedSize: 1012000000
      FileSettings__MaxFileCount: 10

      OpenApisettings__ApiKey: "APIKEY"
      OpenApisettings__ChatCompletionUrl: "https://api.openai.com/v1/chat/completions"
      OpenApisettings__RetryCount: 3
      OpenApisettings__RetryDelaySeconds: 2
      OpenApisettings__MaxToken: 1000

      OAuthGoogleSettings__ClientId: "CLIENTID"
      OAuthGoogleSettings__ClientSecret: "CLIENTSECRET"

    volumes:
      - /home/ubuntu/data/simple_recip_application:/app/Data
