version: '3.8'

services:
  simple_recip_application:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=release

    image: simple_recip_application:1.20.1

    container_name: simple_recip_application

    ports:
      - "4242:4242"

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:4242
      ASPNETCORE_HTTP_PORTS: 4242
      
      ConnectionStrings__DefaultConnection: "Data Source=/app/Data/recipes.db"

      EnableDatabaseLogs: false
      
      ApplicationVersion : "1.13.1"
      
      FeatureManagement__RecipeFeature: true
      FeatureManagement__IngredientFeature: true
      FeatureManagement__ImportationFeature: false
      FeatureManagement__RecipeImportationFeature: true
      FeatureManagement__RecipeManagementFeature: true
      FeatureManagement__IngredientManagementFeature: true
      FeatureManagement__RecipePlanningFeature: true
      FeatureManagement__PlanifiedRecipesAutomaticaly: true
      FeatureManagement__ProductManagementFeature: true
      FeatureManagement__UserPantryManagement: true
      FeatureManagement__TagManagement: true
      FeatureManagement__ShoppingListManagement: true
      FeatureManagement__CalendarManagementFeature: true
      
      FileSettings__MaxAllowedSize: 1012000000
      FileSettings__MaxFileCount: 10

      OpenApisettings__ApiKey: "APIKEY"
      OpenApisettings__ChatCompletionUrl: "https://api.openai.com/v1/chat/completions"
      OpenApisettings__RetryCount: 3
      OpenApisettings__RetryDelaySeconds: 2
      OpenApisettings__MaxToken: 1000

      OAuthGoogleSettings__ClientId: "CLIENTID"
      OAuthGoogleSettings__ClientSecret: "CLIENTSECRET"

      MailtrapSettings__Email: "EMAIL"
      MailtrapSettings__Username: "USERNAME"
      MailtrapSettings__Password: "PASSWORD"
      MailtrapSettings__Host: "HOST"
      MailtrapSettings__Port: 2525

      SimpleRecipeApplicationSettings__BaseUrl: ""
  

    volumes:
      - /home/ubuntu/data/simple_recip_application:/app/Data
