version: '3.8'

services:
  simple_recip_application:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=release

    image: simple_recip_application:1.10.17

    container_name: simple_recip_application

    ports:
      - "4242:4242"

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:4242
      ASPNETCORE_HTTP_PORTS: 4242
      ConnectionStrings__DefaultConnection: "Data Source=/app/Data/recipes.db"
      ApplicationVersion : "1.10.17"
      FeatureManagement__RecipeFeature: false

    volumes:
      - /home/ubuntu/data/simple_recip_application:/app/Data
