using simple_recip_application.Features.IngredientsManagement.ApplicationCore;

namespace simple_recip_application.Features.IngredientsManagement.Store.Actions;

public record AddIngredientAction(IIngredientModel Ingredient);
