using simple_recip_application.Features.NotificationsManagement.ApplicationCore;

namespace simple_recip_application.Features.NotificationsManagement.Store.Actions;

public record class RemoveNotificationAction(INotificationMessage NotificationMessage){}