using simple_recip_application.Features.CalendarUserAccessManagement.ApplicationCore.Entities;

namespace simple_recip_application.Features.CalendarUserAccessManagement.Store.Actions;

public record ShareCalendarAction(ICalendarUserAccessModel CalendarUserAccessModel) {}
public record ShareCalendarSuccessAction{}
public record ShareCalendarFailureAction{}
