using simple_recip_application.Features.PantryIngredientManagement.ApplicationCore.Entities;

namespace simple_recip_application.Features.PantryIngredientManagement.Store.Actions;

// Chargement
public record LoadUserPantryIngredientsAction(string UserId);
public record LoadUserPantryIngredientsSuccessAction(IEnumerable<IUserPantryIngredientModel> Ingredients);
public record LoadUserPantryIngredientsFailureAction();

// Ajout ou mise à jour
public record AddOrUpdateUserPantryIngredientAction(IUserPantryIngredientModel Ingredient);
public record AddOrUpdateUserPantryIngredientSuccessAction(IUserPantryIngredientModel Ingredient);
public record AddOrUpdateUserPantryIngredientFailureAction();

// Suppression
public record DeleteUserPantryIngredientAction(IUserPantryIngredientModel Ingredient);
public record DeleteUserPantryIngredientSuccessAction(IUserPantryIngredientModel Ingredient);
public record DeleteUserPantryIngredientFailureAction(IUserPantryIngredientModel Ingredient);
